<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Silk.NET.Shaderc" />
    <PackageReference Include="Silk.NET.Shaderc.Native" />
    <PackageReference Include="Silk.NET.Vulkan" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" />
    <PackageReference Include="StbImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Utils\Lib.Utils.csproj" />
  </ItemGroup>

</Project>
